"""Crear modelos

Revision ID: 560038f37a66
Revises: 
Create Date: 2022-07-18 23:23:45.645835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560038f37a66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('estado2', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'estado2')
    # ### end Alembic commands ###
